### ISSUE TITLE
'Tools' and 'News'

### ISSUE THREAD

**Issue by britsanto** [minimod-nutrition/minimod-website#17]
@amichuda 
Dr. Vosti informed me that he would like to go over the website tomorrow. I noticed that clicking those tabs would lead me to a page like this:

![Screen Shot 2021-05-12 at 6 38 49 PM](https://user-images.githubusercontent.com/82904227/118065171-63061d00-b351-11eb-8dfe-256a40d2840c.png)

Is there anything I can do to fix this?

**Comment by amichuda** [comment]
@britsanto 
Hmm okay, so in terms of News, that issue comes from there being no `news.md` file, so there's nothing to go to. If you make some basic file and put something like "Coming Soon!" or something that should be enough.

The second is a little weirder... Tools points to a file called `tools/minimod.md`, but that's  actually a folder in the repository called `minimod.md`, which doesn't make sense. `.md` should be files not folders. Do you know why this might have happened?

Third, if Steve is going to look a the website tomorrow, make sure to send me any pull requests so I can merge them and for the website to update. When are you meeting with him tomorrow?

**Comment by britsanto** [comment]
@amichuda Oh, I think the reason why I put it under minimod.md is because I didn't want to accidentally lose the content in the folder and decided to just relocate it under minimod.md.  I think I did send a pull request 5 days ago that edited the tools tab. I doubt it will fix anything though, so it would be better to just ignore it. Could we maybe go over it through zoom? I'm not quite sure on how to approach this.

Dr. Vosti has not yet given me a time, but I can let him know that we are still working on it if we are unable to fix this by then.

**Comment by amichuda** [comment]
Hi Britney,

Yes, I think it's a bit of a pickle. I would try to make minimod.md a file,
with "coming soon" and have it in the same directory as the rest of the
files that are currently in that folder. If that doesn't work, we should
meet on Zoom, but unfortunately, I don't think I can meet tomorrow.

**Comment by amichuda** [comment]
Also, you don't have to ever worry about losing anything because git tracks all changes. So if you ever delete something and you want it back, you can always just go back to that commit and get it

**Comment by britsanto** [comment]
Oh, that's good to know! I was so worried I might accidentally remove something permanently. I have attempted to fix the tools folder. Hope it works!
